import type { Metadata } from "next";
import "./globals.css";
import Pagina from "@/components/template/Pagina";

export const metadata: Metadata = {
  title: "CryptoAdmin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased">
        <Pagina>{children}</Pagina>
      </body>
    </html>
  );
}
